# Generated by Django 2.2 on 2020-07-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='last_name',
        ),
    ]
